FROM node:26-bookworm-slim@sha256:367679cf9792759492a486e4aa4b421764d71a9546a6dae8aab81a99eb797b3e
WORKDIR /src
COPY package.json package-lock.json ./
COPY web/package.json web/package.json
COPY clients/shared/package.json clients/shared/package.json
COPY clients/tizen/package.json clients/tizen/package.json
COPY desktop/package.json desktop/package.json
RUN npm ci
RUN chmod -R a+rwX /src/node_modules
COPY web web
COPY clients clients
CMD ["npm","run","build"]
