FROM node:25-bookworm-slim@sha256:81db02c4b671288a03915da9534dbd54f96d0e7c24d80ccc54f5b36b2e684370
WORKDIR /src
COPY package.json package-lock.json ./
COPY web/package.json web/package.json
COPY clients/shared/package.json clients/shared/package.json
COPY clients/tizen/package.json clients/tizen/package.json
RUN npm ci
RUN chmod -R a+rwX /src/node_modules
COPY web web
COPY clients clients
CMD ["npm","run","build"]
